services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 3002:3002
    # turn this on for local development on a local docker instance
    # env_file: ".env"
