services:
  server:
    image: glitch003/mcpwrapper
    environment:
      - PORT=3002
      - NODE_ENV=production
      - COMPOSIO_API_KEY=${COMPOSIO_API_KEY}
      - COMPOSIO_GMAIL_INTEGRATION_ID=${COMPOSIO_GMAIL_INTEGRATION_ID}
      - COMPOSIO_FB_INTEGRATION_ID=${COMPOSIO_FB_INTEGRATION_ID}
    ports:
      - 3002:3002
    volumes:
    - /var/run/tappd.sock:/var/run/tappd.sock
